import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>블로그에 와주셔서 감사합니다</h1>

        <p className={styles.description}>
          편하게 구경하고 가세요
          <code className={styles.code}>good</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>데스크톱이시면 &larr;</h2>
            <p>왼쪽에 마우스를 옮겨보시면 메뉴가 나옵니다</p>
          </a>

          <a className={styles.card}>
            <h2>모바일이시면 &uarr;</h2>
            <p>스크롤을 아래로 하시면 메뉴가 뜰 겁니다</p>
          </a>

          <a
            href="https://github.com/sungguenja"
            target={"_blank"}
            className={styles.card}
          >
            <h2>이 사람의 깃허브 &rarr;</h2>
            <p>
              그간 공부한 것과 만들어 본 것들이 모여있습니다 (포트폴리오 페이지
              추후 제공 예정)
            </p>
          </a>

          <a className={styles.card}>
            <h2>아무쪼록</h2>
            <p>와주셔서 정말 감사합니다</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
