# Generated by Django 3.2.7 on 2021-10-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_url', models.TextField(default='No')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.article')),
                ('hashtag_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.hashtag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='menu_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.menu'),
        ),
    ]
