# Generated by Django 3.2.7 on 2022-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20211221_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymousName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='anonymousPassword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
