# Generated by Django 3.2.7 on 2022-02-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_auto_20220131_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='anonymousName',
            new_name='anonymous_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='anonymousPassword',
            new_name='anonymous_password',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='isAnonymous',
            new_name='is_anonymous',
        ),
    ]
