# Generated by Django 3.2.7 on 2022-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
